//var http = require('http');
//var fs = require('fs');
//
//http.createServer(function (request, response) {
//	if (request.method == 'GET') {
//		fs.readFile('HTMLPage.htm', function (error, data) {
//			response.writeHead(200, { 'Content-Type': 'text/html'})
//			response.end(data);
//		});
//	} else if (request.method == 'POST') {
//		request.on('data', function (data) {
//			response.write("");
//			response.write("<!DOCTYPE html>");
//			response.write("<html lang='en'>");
//			response.write("<head>");
//			response.write("<meta charset='utf-8'>");
//			response.write("<meta name='viewport' content='width=device-width, initial-scale=1.0'>");
//			response.write("<meta name='description' content=''>");
//			response.write("<meta name='author' content='Dashboard'>");
//			response.write("<meta name='keyword'");
//			response.write("content='Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina'>");
//
//			response.write("<title>DASHGUM - FREE Bootstrap Admin Template</title>");
//
//			response.write("<link href='../css/bootstrap.css' rel='stylesheet'>");
//			response.write("<link href='../font-awesome/css/font-awesome.css' rel='stylesheet' />");
//			response.write("	<link rel='stylesheet' type='text/css' href='../css/zabuto_calendar.css'>");
//			response.write("	<link rel='stylesheet' type='text/css'");
//			response.write("		href='../js/gritter/css/jquery.gritter.css' />");
//			response.write("			<link rel='stylesheet' type='text/css' href='../lineicons/style.css'>");
//
//			response.write("<link href='../css/style.css' rel='stylesheet'>");
//			response.write("<link href='../css/style-responsive.css' rel='stylesheet'>");
//
//			response.write("</head>");
//			response.write("<body>");
//
//			response.write("<div id='login-page'>");
//			response.write("<div class='container'>");
//			response.write("	<div aria-hidden='true' aria-labelledby='myModalLabel' role='dialog'");
//			response.write("	id='myModal1' class='modal fade'>");
//			response.write("<form class='form-login' action='auth.html'>");
//			response.write("<div class='modal-header'>");
//			response.write("<h2 class='form-login-heading'>sign in now</h2>");
//			response.write("</div>");
//			response.write("<div class='login-wrap'>");
//			response.write("<input type='text' class='form-control' placeholder='User ID'");
//			response.write("	autofocus> <br> <input type='password'");
//			response.write("	class='form-control' placeholder='Password'> <label");
//			response.write("	class='checkbox'> <span class='pull-right'> <a");
//			response.write("	data-toggle='modal' href='../index.html#myModal2'> Forgot");
//			response.write("	Password?</a>");
//			response.write("	</span>");
//			response.write("	</label>");
//			response.write("	<button class='btn btn-theme btn-block' href='../index.html'");
//			response.write("	type='submit'>");
//			response.write("	<i class='fa fa-lock'></i> SIGN IN");
//			response.write("	</button>");
//			response.write("	<hr>");
//			response.write("	<div class='login-social-link centered'>");
//			response.write("	<p>or you can sign in via your social network</p>");
//			response.write("	<button class='btn btn-facebook' type='submit'>");
//			response.write("	<i class='fa fa-facebook'></i> Facebook");
//			response.write("	</button>");
//			response.write("	</div>");
//			response.write("	<div class='registration'>");
//			response.write("	Don't have an account yet?<br /> <a class='' href='#'>");
//			response.write("	Create an account </a>");
//			response.write("	</div>");
//			response.write("	</div>");
//			response.write("	</form>");
//			response.write("	</div>");
//
//			response.write("	<div aria-hidden='true' aria-labelledby='myModalLabel' role='dialog'");
//			response.write("	tabindex='-1' id='myModal2' class='modal fade'>");
//			response.write("	<div class='modal-dialog'>");
//			response.write("	<div class='modal-content'>");
//			response.write("	<div class='modal-header'>");
//			response.write("	<button type='button' class='close' data-dismiss='modal'");
//			response.write("	aria-hidden='true'>&times;</button>");
//			response.write("	<h4 class='modal-title'>Forgot Password ?</h4>");
//			response.write("	</div>");
//			response.write("	<div class='modal-body'>");
//			response.write("	<p>Enter your e-mail address below to reset your password.</p>");
//			response.write("	<input type='text' name='email' placeholder='Email'");
//			response.write("	autocomplete='off' class='form-control placeholder-no-fix'>");
//			response.write("	</div>");
//			response.write("	<div class='modal-footer'>");
//			response.write("	<button data-dismiss='modal' class='btn btn-default'");
//			response.write("		type='button'>Cancel</button>");
//			response.write("	<button class='btn btn-theme' type='button'>Submit</button>");
//			response.write("	</div>");
//			response.write("	</div>");
//			response.write("	</div>");
//			response.write("				</div>");
//
//			response.write("				</div>");
//			response.write("				</div>");
//
//			response.write("				<section id='container' class='sidebar-closed'>");
//			response.write("				<header class='header black-bg'>");
//			response.write("				<div class='sidebar-toggle-box'>");
//			response.write("				<div class='fa fa-bars tooltips' data-placement='right'");
//			response.write("					data-original-title='Toggle Navigation'></div>");
//			response.write("					</div>");
//			response.write("					<a href='index.html' class='logo'> <img id='wecando_white'");
//			response.write("						src='../img/wecando_white.png'>");
//			response.write("					</a>");
//			response.write("					<div class='top-menu'>");
//			response.write("					<ul class='nav pull-right top-menu'>");
//			response.write("					<li><a class='logout' data-toggle='modal'");
//			response.write("						href='../index.html#myModal1'>Logout</a></li>");
//			response.write("						</ul>");
//			response.write("						</div>");
//			response.write("						</header>");
//			response.write("						<aside>");
//			response.write("						<div id='sidebar' class='nav-collapse '>");
//			response.write("						<ul class='sidebar-menu' id='nav-accordion'>");
//			response.write("						<li class='sub-menu'><a href='../javascript:;'> <i");
//			response.write("						class='fa fa-calendar'></i> <span>예약 정보</span>");
//			response.write("						</a>");
//			response.write("						<ul class='sub'>");
//			response.write("						<li><a href='../general.html'>General</a></li>");
//			response.write("					<li><a href='../buttons.html'>Buttons</a></li>");
//			response.write("					<li><a href='../panels.html'>Panels</a></li>");
//			response.write("					</ul></li>");
//
//			response.write("					<li class='sub-menu'><a href='../javascript:;'> <i");
//			response.write("					class='fa fa-user'></i> <span>마이 페이지</span>");
//			response.write("					</a>");
//			response.write("					<ul class='sub'>");
//			response.write("					<li><a href='../calendar.html'>Calendar</a></li>");
//			response.write("					<li><a href='../gallery.html'>Gallery</a></li>");
//			response.write("					<li><a href='../todo_list.html'>Todo List</a></li>");
//			response.write("					</ul></li>");
//			response.write("					</ul>");
//			response.write("					</div>");
//			response.write("					</aside>");
//			response.write("					<section id='main-content'>");
//			response.write("						<section class='wrapper'>");
//			response.write("						<div id='auth'>");
//			response.write("					<img id='joinus' src='../img/joinus.png'>");
//			response.write("					<div class='row mtbox'>");
//			response.write("					<div class='col-md-4 col-md-offset-1 box0'>");
//			response.write("					<div class='box1'>");
//			response.write("					<span class='li_user'></span>");
//			response.write("					<form action='join.html' method='post'>");
//			response.write("					<input type='hidden' id='#hi'> <input type='hidden'");
//			response.write("						name='m_email'> <input type='hidden' name='email_code'>");
//			response.write("						</form>");
//			response.write("					<h3>개인 회원</h3>");
//			response.write("						</div>");
//			response.write("						<p>학교 시설을 예약하고 사용하실 수 있습니다.</p>");
//			response.write("						</div>");
//			response.write("						<div class='col-md-4 box0'>");
//			response.write("						<div class='box1'>");
//			response.write("						<span class='li_shop'></span> <a href='join.html'></a>");
//			response.write("						<h3>학교 관리자</h3>");
//			response.write("						</div>");
//			response.write("						<p>학교 시설을 등록하고 대관할 수 있습니다.</p>");
//			response.write("						</div>");
//			response.write("						</div>");
//			response.write("						</div>");
//			response.write("					</section>");
//			response.write("					</section>");
//			response.write("						</section>");
//			response.write("							<script src='../js/jquery.js'></script>");
//			response.write("							<script src='../js/jquery-1.8.3.min.js'></script>");
//			response.write("							<script src='../js/bootstrap.min.js'></script>");
//			response.write("							<script class='include' type='text/javascript'");
//			response.write("								src='../js/jquery.dcjqaccordion.2.7.js'></script>");
//			response.write("								<script src='../js/jquery.scrollTo.min.js'></script>");
//			response.write("								<script src='../js/jquery.nicescroll.js' type='text/javascript'></script>");
//			response.write("								<script src='../js/jquery.sparkline.js'></script>");
//			response.write("								<script src='../js/common-scripts.js'></script>");
//			response.write("								<script>");
//			response.write("								$(document).ready(function() {");
//			response.write("					var show = $('#hi');");
//			response.write("					response.write("	);							
//			response.write("						console.log(request);");
//			response.write("console.log(request.param);");
//			response.write("var form_data = new FormData();");
//			response.write("form_data.append('m_email', $('#m_email').val())");
//			response.write("form_data.append('email_code', $('#email_code').val())");
//			response.write("$.ajax({");
//			response.write("	url : contextRoot + '/member/ajax/choose_auth.do',");
//			response.write("	type : 'post',");
//			response.write("	dataType : 'json',");
//			response.write("	async : false,");
//			response.write("	cache : false,");
//			response.write("	contentType : false,");
//			response.write("	processData : false,");
//			response.write("	data : form_data,");
//			response.write("	success : function(resultObj) {");
//			response.write("		var ajaxResult = resultObj.ajaxResult;");
//			response.write("		if (ajaxResult.status == 'success') {");
//			response.write("			swal('Good job!', 'Email 전송이 완료되었습니다', 'success')");
//			response.write("			e.preventDefault();");
//			response.write("		} else {");
//			response.write("			sweetAlert('Oops...', '다시 시도해 주세요', 'error');");
//			response.write("			e.preventDefault();");
//			response.write("		}");
//			response.write("		}");
//			response.write("	})");
//			response.write("});");
//			response.write("</script>");
//			response.write("				</body>");
//			response.write("				</html>");
//		});
//	}
//}).listen('localhost:8080/wecando/loginpage/choose_auth.html', function(){
//	console.log('Server Running at http://localhost:8080')
//})
