-- 학교
CREATE TABLE SCHOOL (
	 SCH_NUM       INTEGER      NOT NULL, -- 학교번호
	 SCH_NAME      VARCHAR(50)  NOT NULL, -- 학교명
	 SCH_LOCATION  VARCHAR(255) NOT NULL, -- 위치
	 SCH_TEL       VARCHAR(30)  NOT NULL, -- 전화번호
	 SCH_DATE      DATE         NOT NULL, -- 이용가능날짜
	 SCH_TIME      VARCHAR(255) NOT NULL, -- 이용가능시간
	 MEMBER_NUM    INTEGER      NULL      -- 회원번호
);

-- 학교
ALTER TABLE SCHOOL
	ADD CONSTRAINT  PK_SCHOOL  -- 학교 기본키
		PRIMARY KEY (
			 SCH_NUM  -- 학교번호
		);

ALTER TABLE SCHOOL
	MODIFY COLUMN  SCH_NUM  INTEGER NOT NULL AUTO_INCREMENT;

-- 예약
CREATE TABLE   RESERVE  (
	 RESERVE_NUM     INTEGER  NOT NULL, -- 예약번호
	 RESERVE_PERSON  INTEGER  NOT NULL, -- 사용인원
	 RESERVE_PRO     CHAR(10) NOT NULL, -- 예약진행여부
	 RESERVE_DATE    DATE     NOT NULL, -- 예약신청일
	 SCH_NUM         INTEGER  NULL,     -- 학교번호
	 EVENT_CODE      CHAR(10) NULL,     -- 종목코드
	 MEMBER_NUM      INTEGER  NULL      -- 회원번호
);

-- 예약
ALTER TABLE   RESERVE 
	ADD CONSTRAINT  PK_RESERVE  -- 예약 기본키
		PRIMARY KEY (
			 RESERVE_NUM  -- 예약번호
		);

ALTER TABLE   RESERVE 
	MODIFY COLUMN  RESERVE_NUM  INTEGER NOT NULL AUTO_INCREMENT;

-- 종목
CREATE TABLE   EVENT  (
	 EVENT_CODE   CHAR(10)    NOT NULL, -- 종목코드
	 EVENT_NAME   VARCHAR(50) NOT NULL, -- 종목명
	 EVENT_MAX    INTEGER     NOT NULL, -- 최대수용인원
	 EVENT_PRICE  INTEGER     NOT NULL  -- 사용금액
);

-- 종목
ALTER TABLE   EVENT 
	ADD CONSTRAINT  PK_EVENT  -- 종목 기본키
		PRIMARY KEY (
			 EVENT_CODE  -- 종목코드
		);

-- Q&A
CREATE TABLE   BOARD  (
	 BOARD_NUM      INTEGER      NOT NULL, -- 게시글번호
	 BOARD_CONTENT  VARCHAR(255) NOT NULL, -- 게시글내용
	 BOARD_PWD      VARCHAR(100) NULL,     -- 게시글비밀번호
	 MEMBER_NUM     INTEGER      NULL,     -- 회원번호
	 SCH_NUM        INTEGER      NULL      -- 학교번호
);

-- Q&A
ALTER TABLE   BOARD 
	ADD CONSTRAINT  PK_BOARD  -- Q&A 기본키
		PRIMARY KEY (
			 BOARD_NUM  -- 게시글번호
		);

ALTER TABLE   BOARD 
	MODIFY COLUMN  BOARD_NUM  INTEGER NOT NULL AUTO_INCREMENT;

-- 사진
CREATE TABLE   PHOTO  (
	 PHOTO_NUM   INTEGER      NOT NULL, -- 사진번호
	 PHOTO_NAME  VARCHAR(255) NOT NULL, -- 사진명
	 SCH_NUM     INTEGER      NULL,     -- 학교번호
	 BOARD_NUM   INTEGER      NULL      -- 게시글번호
);

-- 사진
ALTER TABLE   PHOTO 
	ADD CONSTRAINT  PK_PHOTO  -- 사진 기본키
		PRIMARY KEY (
			 PHOTO_NUM  -- 사진번호
		);

ALTER TABLE   PHOTO 
	MODIFY COLUMN  PHOTO_NUM  INTEGER NOT NULL AUTO_INCREMENT;

-- 회원
CREATE TABLE   MEMBER  (
	 MEMBER_NUM    INTEGER      NOT NULL, -- 회원번호
	 MEMBER_GRADE  INTEGER      NOT NULL, -- 회원등급
	 MEMBER_EMAIL  VARCHAR(40)  NOT NULL, -- 이메일
	 MEMBER_NAME   VARCHAR(50)  NOT NULL, -- 회원명
	 MEMBER_TEL    VARCHAR(30)  NOT NULL, -- 전화번호
	 MEMBER_PWD    VARCHAR(100) NOT NULL, -- 비밀번호
	 MEMBER_AVA    INTEGER      NOT NULL  -- 예약가능여부
);

-- 회원
ALTER TABLE   MEMBER 
	ADD CONSTRAINT  PK_MEMBER  -- 회원 기본키
		PRIMARY KEY (
			 MEMBER_NUM  -- 회원번호
		);

ALTER TABLE   MEMBER 
	MODIFY COLUMN  MEMBER_NUM  INTEGER NOT NULL AUTO_INCREMENT;

-- 답글
CREATE TABLE   REPLY  (
	 REPLY_NUM      INTEGER      NOT NULL, -- 답글번호
	 REPLY_CONTENT  VARCHAR(255) NOT NULL, -- 답글내용
	 BOARD_NUM      INTEGER      NULL,     -- 게시글번호
	 MEMBER_NUM     INTEGER      NULL      -- 회원번호
);

-- 답글
ALTER TABLE   REPLY 
	ADD CONSTRAINT  PK_REPLY  -- 답글 기본키
		PRIMARY KEY (
			 REPLY_NUM  -- 답글번호
		);

ALTER TABLE   REPLY 
	MODIFY COLUMN  REPLY_NUM  INTEGER NOT NULL AUTO_INCREMENT;

-- 학교종목
CREATE TABLE   SCHEVENT  (
	 EVENT_CODE  CHAR(10) NULL, -- 종목코드
	 SCH_NUM     INTEGER  NULL  -- 학교번호
);

-- 학교
ALTER TABLE   SCHOOL 
	ADD CONSTRAINT  FK_MEMBER_TO_SCHOOL  -- 회원 -> 학교
		FOREIGN KEY (
			 MEMBER_NUM  -- 회원번호
		)
		REFERENCES   MEMBER  ( -- 회원
			 MEMBER_NUM  -- 회원번호
		);

-- 예약
ALTER TABLE   RESERVE 
	ADD CONSTRAINT  FK_SCHOOL_TO_RESERVE  -- 학교 -> 예약
		FOREIGN KEY (
			 SCH_NUM  -- 학교번호
		)
		REFERENCES   SCHOOL  ( -- 학교
			 SCH_NUM  -- 학교번호
		);

-- 예약
ALTER TABLE   RESERVE 
	ADD CONSTRAINT  FK_EVENT_TO_RESERVE  -- 종목 -> 예약
		FOREIGN KEY (
			 EVENT_CODE  -- 종목코드
		)
		REFERENCES   EVENT  ( -- 종목
			 EVENT_CODE  -- 종목코드
		);

-- 예약
ALTER TABLE   RESERVE 
	ADD CONSTRAINT  FK_MEMBER_TO_RESERVE  -- 회원 -> 예약
		FOREIGN KEY (
			 MEMBER_NUM  -- 회원번호
		)
		REFERENCES   MEMBER  ( -- 회원
			 MEMBER_NUM  -- 회원번호
		);

-- Q&A
ALTER TABLE   BOARD 
	ADD CONSTRAINT  FK_MEMBER_TO_BOARD  -- 회원 -> Q&A
		FOREIGN KEY (
			 MEMBER_NUM  -- 회원번호
		)
		REFERENCES   MEMBER  ( -- 회원
			 MEMBER_NUM  -- 회원번호
		);

-- Q&A
ALTER TABLE   BOARD 
	ADD CONSTRAINT  FK_SCHOOL_TO_BOARD  -- 학교 -> Q&A
		FOREIGN KEY (
			 SCH_NUM  -- 학교번호
		)
		REFERENCES   SCHOOL  ( -- 학교
			 SCH_NUM  -- 학교번호
		);

-- 사진
ALTER TABLE   PHOTO 
	ADD CONSTRAINT  FK_SCHOOL_TO_PHOTO  -- 학교 -> 사진
		FOREIGN KEY (
			 SCH_NUM  -- 학교번호
		)
		REFERENCES   SCHOOL  ( -- 학교
			 SCH_NUM  -- 학교번호
		);

-- 사진
ALTER TABLE   PHOTO 
	ADD CONSTRAINT  FK_BOARD_TO_PHOTO  -- Q&A -> 사진
		FOREIGN KEY (
			 BOARD_NUM  -- 게시글번호
		)
		REFERENCES   BOARD  ( -- Q&A
			 BOARD_NUM  -- 게시글번호
		);

-- 답글
ALTER TABLE   REPLY 
	ADD CONSTRAINT  FK_BOARD_TO_REPLY  -- Q&A -> 답글
		FOREIGN KEY (
			 BOARD_NUM  -- 게시글번호
		)
		REFERENCES   BOARD  ( -- Q&A
			 BOARD_NUM  -- 게시글번호
		);

-- 답글
ALTER TABLE   REPLY 
	ADD CONSTRAINT  FK_MEMBER_TO_REPLY  -- 회원 -> 답글
		FOREIGN KEY (
			 MEMBER_NUM  -- 회원번호
		)
		REFERENCES   MEMBER  ( -- 회원
			 MEMBER_NUM  -- 회원번호
		);

-- 학교종목
ALTER TABLE   SCHEVENT 
	ADD CONSTRAINT  FK_EVENT_TO_SCHEVENT  -- 종목 -> 학교종목
		FOREIGN KEY (
			 EVENT_CODE  -- 종목코드
		)
		REFERENCES   EVENT  ( -- 종목
			 EVENT_CODE  -- 종목코드
		);

-- 학교종목
ALTER TABLE   SCHEVENT 
	ADD CONSTRAINT  FK_SCHOOL_TO_SCHEVENT  -- 학교 -> 학교종목
		FOREIGN KEY (
			 SCH_NUM  -- 학교번호
		)
		REFERENCES   SCHOOL  ( -- 학교
			 SCH_NUM  -- 학교번호
		);